### ISSUE TITLE
home.html Шапка и слайдер

### ISSUE THREAD

**Issue by V1RUSBOY** [V1RUSBOY/html_group_9_teamwork_team_4#1]
Сверстать:
1. Шапку 
2. Слайдер, желательно с использованием Slick'a 
Плюс ко всему нужна адаптивность, а также кроссбраузерность, как минимум в таких браузерах как:
Chrome, Microsoft Edge, Firefox Mozilla
Время по плану: 3 часа
-----------------------------------------------------------------------------
Исполнитель: Alexander

**Comment by AlexanderKim3125** [comment]
Сверстал адаптивную и кроссбраузерную шапку со слайдером
Время по факту: 4 часа
