### ISSUE TITLE
Исправить баг со слайдерами 

### ISSUE THREAD

**Issue by V1RUSBOY** [V1RUSBOY/html_group_9_teamwork_team_4#13]
Все слайдеры на Slick'e полетели (кажется Slick тупо перестал работать, поройся в core.js проверь, там все), нужно поправить
Время по плану: 1 час

-----------------------------------------
Исполнитель: Александр

**Comment by AlexanderKim3125** [comment]
Исправил баг со слайдерами, внес изменения в файл core.js
Время по факту: 30 мин
