### ISSUE TITLE
Нужно по вставлять в теги "a" нужные ссылки

### ISSUE THREAD

**Issue by V1RUSBOY** [V1RUSBOY/html_group_9_teamwork_team_4#14]
Нужно по вставлять в теги "a" нужные ссылки, чтобы все страницы были связаны друг с другом, 
также проверить чтобы все работало корректно
-----------------------------------
Исполнитель: Anybody

**Comment by AlexanderKim3125** [comment]
Переходы по ссылкам работают корректно
Время по факту: 20 минут
