### ISSUE TITLE
home.html Белый блок "testimonials", Синий блок-форму, Футер

### ISSUE THREAD

**Issue by V1RUSBOY** [V1RUSBOY/html_group_9_teamwork_team_4#2]
Сверстать:
1. Белый блок "testimonials"
2. Синий блок-форму с использованием иконочного шрифта или спрайта
3. Футер 
Все блоки будут использоваться и на других страницах, так что сверстать нужно секциями
Плюс ко всему нужна адаптивность, а также кроссбраузерность, как минимум в таких браузерах как:
Chrome, Microsoft Edge, Firefox Mozilla
Время по плану: 2.5 часа
-----------------------------------------------------------------------------
Исполнитель: Тима

**Comment by ttttimaaaa** [comment]
Сверстано, проверено на адаптивность и кроссбраузерность.
Время по факту 3 часа
