### ISSUE TITLE
home.html Контент блок и слайдер№2

### ISSUE THREAD

**Issue by V1RUSBOY** [V1RUSBOY/html_group_9_teamwork_team_4#3]
Сверстать:
1. Контент блок
2. Слайдер №2 желательно с использованием Slick'a 
Плюс ко всему нужна адаптивность, а также кроссбраузерность, как минимум в таких браузерах как:
Chrome, Microsoft Edge, Firefox Mozilla
Время по плану: 3.5 часа
------------------------------------------------------------------------------
Исполнитель: Alexander

**Comment by AlexanderKim3125** [comment]
Сверстано, проверено на адаптивность и кроссбраузерность.
Время по факту: 4 часа
