### ISSUE TITLE
our-works.html Our Works блок

### ISSUE THREAD

**Issue by V1RUSBOY** [V1RUSBOY/html_group_9_teamwork_team_4#6]
Сверстать:
1. Our Works block 
2. Зеленая полоска 
Плюс ко всему нужна адаптивность, а также кроссбраузерность, как минимум в таких браузерах как:
Chrome, Microsoft Edge, Firefox Mozilla
Время по плану:  3.5 часа
------------------------------------------------------------------
Исполнитель: Александр

**Comment by AlexanderKim3125** [comment]
Сверстано, проверено на адаптивность и кроссбраузерность.
Время по факту: 3 часа
